feature: add Popup Discussion
magang-mknows/kg pull request #12
Opened 2023-03-23 10:02 UTC by fauzannmw

2023-03-23 10:42 UTC, bangmar approved these changes

2023-03-24 04:00 UTC, maulanasdqn requested changes
semua PopUp harus di wrap pake SuspenseError buat ningkatin performa

2023-03-24 04:00 UTC, maulanasdqn commented on src/modules/DiscussionRoom/Content/index.tsx
> +      <PopupModalCreateDiscussion />
tiap pop up harus di wrap pake SuspenseError buat ningkatin performa

2023-03-24 08:07 UTC, fauzannmw commented on src/modules/DiscussionRoom/Content/index.tsx
> +      <PopupModalCreateDiscussion />
done bang

2023-03-24 08:22 UTC, maulanasdqn approved these changes

2023-03-24 08:23 UTC, merged